#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application as ConsoleApplication;

$app = new ConsoleApplication('My CLI Application', '0.1.0');
$app->addCommands(array(
    new Purger\Command\FlushCommand(),
    new Purger\Command\ListenCommand(),
    new Purger\Command\StatusCommand(),
));

$app->run();