parameters:
  config_filename : "app/config.yml"
  console_commands :
    - @command_blank
    - @command_flush
    - @command_listen
    - @command_status

services:
  config:
    class: Purger\Config\Config
    arguments : [ %config_filename% ]
  command_blank:
    class: Purger\Command\BlankCommand
    calls:
      - [setConfig,  [@config]]
  command_flush:
    class: Purger\Command\FlushCommand
    calls:
      - [setConfig,  [@config]]
  command_listen:
    class: Purger\Command\ListenCommand
    calls:
      - [setConfig,  [@config]]
  command_status:
    class: Purger\Command\StatusCommand
    calls:
      - [setConfig,  [@config]]
  console:
    class: Symfony\Component\Console\Application
    calls:
      - [addCommands, [ %console_commands% ] ]
